"""Generate a clearly labelled SIMULATED ELISA dataset for pipeline development.

Nothing produced by this script comes from an experiment. Optical densities are
drawn from a defined four-parameter logistic (4PL) curve with a stochastic noise
model, using a fixed random seed so the output is reproducible. No instrument,
kit, lot, operator, or storage location is represented, because none exists.

Outputs (all under data/simulated_elisa/, all prefixed SIMULATED_):

  SIMULATED_elisa_plate_NN_OD.csv      8 x 12 plate-format OD grid, one per plate
  SIMULATED_elisa_plate_NN_layout.csv  well -> role / sample id / nominal standard
  SIMULATED_elisa_long.csv             one row per well across all plates (ingest this)
  SIMULATED_elisa_ground_truth.csv     true concentration of every sample and QC
  SIMULATED_elisa_parameters.json      seed, 4PL parameters, noise model

Every CSV opens with '# SIMULATED DATA' comment lines; read with comment='#'.

Usage:
    python3 src/simulate_elisa.py [--plates 3] [--seed 20260927] [--cv 0.04]
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import os
import random

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DEFAULT = os.path.join(ROOT, "data", "simulated_elisa")

ROWS = "ABCDEFGH"
COLS = list(range(1, 13))

# ---------------------------------------------------------------------------
# Defined 4PL standard curve.  OD = D + (A - D) / (1 + (x / C) ** B)
# A = response at zero concentration, D = response at infinite concentration,
# C = inflection point (EC50), B = Hill slope.  Units: pg/mL, OD (dimensionless).
# ---------------------------------------------------------------------------
FOUR_PL = {"A": 0.060, "B": 1.15, "C": 260.0, "D": 3.10}

STANDARD_TOP_PG_ML = 2000.0
STANDARD_DILUTION = 2.0
N_STANDARDS = 8                       # S1 (top) .. S8, 2-fold series
QC_LEVELS = {"QC-LOW": 60.0, "QC-HIGH": 900.0}

NOISE = {
    "well_cv": 0.04,                  # multiplicative, lognormal, per well
    "read_sd_od": 0.008,              # additive Gaussian, per well
    "plate_drift_sd": 0.03,           # multiplicative, per plate
    "edge_bias": 0.02,                # multiplicative on outer wells
    "saturation_od": 4.000,           # ceiling applied to every well
    "sample_conc_log10_range": (1.0, 3.5),   # unknowns: 10 .. ~3160 pg/mL
}

HEADER_LINES = [
    "# SIMULATED DATA - not from any experiment.",
    "# Generated by src/simulate_elisa.py from a defined 4PL curve plus a stochastic noise model.",
    "# No instrument, kit, lot, operator, or storage location is represented.",
]


def four_pl(x: float, p: dict) -> float:
    if x <= 0:
        return p["A"]
    return p["D"] + (p["A"] - p["D"]) / (1.0 + (x / p["C"]) ** p["B"])


def is_edge(row: str, col: int) -> bool:
    return row in ("A", "H") or col in (1, 12)


def plate_layout(plate_no: int, sample_ids: list[str]) -> list[dict]:
    """Columns 1-2: standards S1..S8 in duplicate.  Columns 3-12: five duplicate
    pairs x 8 rows = 40 slots: 1 blank, 2 QC, 37 unknowns."""
    wells = []
    standards = [STANDARD_TOP_PG_ML / STANDARD_DILUTION ** i for i in range(N_STANDARDS)]
    for i, row in enumerate(ROWS):
        for col in (1, 2):
            wells.append({
                "well": f"{row}{col}", "row": row, "col": col, "role": "standard",
                "sample_id": f"S{i + 1}", "nominal_pg_mL": standards[i],
            })
    slots = [(row, pair) for pair in range(5) for row in ROWS]  # 40 slots
    roles = [("blank", "BLANK", 0.0)]
    roles += [("qc", name, conc) for name, conc in QC_LEVELS.items()]
    roles += [("unknown", sid, None) for sid in sample_ids]
    assert len(roles) == len(slots), (len(roles), len(slots))
    for (row, pair), (role, sid, nominal) in zip(slots, roles):
        for col in (3 + 2 * pair, 4 + 2 * pair):
            wells.append({
                "well": f"{row}{col}", "row": row, "col": col, "role": role,
                "sample_id": sid, "nominal_pg_mL": nominal,
            })
    for w in wells:
        w["plate"] = plate_no
    return wells


def simulate_od(true_conc: float, rng: random.Random, plate_factor: float,
                edge: bool, noise: dict, p: dict) -> float:
    expected = four_pl(true_conc, p)
    sigma = math.sqrt(math.log(1.0 + noise["well_cv"] ** 2))
    mult = math.exp(rng.gauss(-0.5 * sigma ** 2, sigma))
    od = expected * mult * plate_factor
    if edge:
        od *= 1.0 + noise["edge_bias"]
    od += rng.gauss(0.0, noise["read_sd_od"])
    od = max(0.0, min(noise["saturation_od"], od))
    return round(od, 3)


def write_csv(path: str, fieldnames: list[str], rows: list[dict]) -> None:
    with open(path, "w", newline="", encoding="utf-8") as fh:
        for line in HEADER_LINES:
            fh.write(line + "\n")
        w = csv.DictWriter(fh, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)


def write_plate_grid(path: str, plate_no: int, od_by_well: dict[str, float]) -> None:
    with open(path, "w", newline="", encoding="utf-8") as fh:
        for line in HEADER_LINES:
            fh.write(line + "\n")
        fh.write(f"# plate {plate_no:02d}, raw OD, 8 rows x 12 columns\n")
        w = csv.writer(fh)
        w.writerow([f"SIMULATED_plate_{plate_no:02d}"] + [str(c) for c in COLS])
        for row in ROWS:
            w.writerow([row] + [f"{od_by_well[f'{row}{c}']:.3f}" for c in COLS])


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--plates", type=int, default=3)
    ap.add_argument("--seed", type=int, default=20260927)
    ap.add_argument("--cv", type=float, default=NOISE["well_cv"], help="per-well CV")
    ap.add_argument("--out", default=OUT_DEFAULT)
    args = ap.parse_args()

    noise = dict(NOISE, well_cv=args.cv)
    rng = random.Random(args.seed)
    os.makedirs(args.out, exist_ok=True)

    lo, hi = noise["sample_conc_log10_range"]
    long_rows: list[dict] = []
    truth_rows: list[dict] = []
    sample_counter = 0

    for plate_no in range(1, args.plates + 1):
        ids = [f"SIM-{sample_counter + i + 1:03d}" for i in range(37)]
        sample_counter += 37
        true_conc = {sid: 10 ** rng.uniform(lo, hi) for sid in ids}
        true_conc.update(QC_LEVELS)
        true_conc["BLANK"] = 0.0

        plate_factor = math.exp(rng.gauss(0.0, noise["plate_drift_sd"]))
        layout = plate_layout(plate_no, ids)
        od_by_well: dict[str, float] = {}
        for w in layout:
            conc = w["nominal_pg_mL"] if w["role"] == "standard" else true_conc[w["sample_id"]]
            od = simulate_od(conc, rng, plate_factor, is_edge(w["row"], w["col"]), noise, FOUR_PL)
            od_by_well[w["well"]] = od
            long_rows.append({
                "data_status": "SIMULATED", "plate": plate_no, "well": w["well"],
                "row": w["row"], "col": w["col"], "role": w["role"],
                "sample_id": w["sample_id"],
                "nominal_pg_mL": "" if w["nominal_pg_mL"] is None else f"{w['nominal_pg_mL']:.4g}",
                "od": f"{od:.3f}",
            })

        write_plate_grid(os.path.join(args.out, f"SIMULATED_elisa_plate_{plate_no:02d}_OD.csv"),
                         plate_no, od_by_well)
        write_csv(os.path.join(args.out, f"SIMULATED_elisa_plate_{plate_no:02d}_layout.csv"),
                  ["data_status", "plate", "well", "role", "sample_id", "nominal_pg_mL"],
                  [{"data_status": "SIMULATED", "plate": plate_no, "well": w["well"],
                    "role": w["role"], "sample_id": w["sample_id"],
                    "nominal_pg_mL": "" if w["nominal_pg_mL"] is None else f"{w['nominal_pg_mL']:.4g}"}
                   for w in layout])

        for sid in ids + list(QC_LEVELS) + ["BLANK"]:
            wells = [w["well"] for w in layout if w["sample_id"] == sid]
            role = next(w["role"] for w in layout if w["sample_id"] == sid)
            truth_rows.append({
                "data_status": "SIMULATED", "plate": plate_no, "sample_id": sid, "role": role,
                "true_pg_mL": f"{true_conc[sid]:.4f}", "wells": ";".join(wells),
                "plate_drift_factor": f"{plate_factor:.4f}",
            })

    write_csv(os.path.join(args.out, "SIMULATED_elisa_long.csv"),
              ["data_status", "plate", "well", "row", "col", "role", "sample_id",
               "nominal_pg_mL", "od"], long_rows)
    write_csv(os.path.join(args.out, "SIMULATED_elisa_ground_truth.csv"),
              ["data_status", "plate", "sample_id", "role", "true_pg_mL", "wells",
               "plate_drift_factor"], truth_rows)
    with open(os.path.join(args.out, "SIMULATED_elisa_parameters.json"), "w", encoding="utf-8") as fh:
        json.dump({
            "data_status": "SIMULATED - not from any experiment",
            "generator": "src/simulate_elisa.py",
            "seed": args.seed, "plates": args.plates,
            "four_pl": FOUR_PL,
            "four_pl_form": "OD = D + (A - D) / (1 + (x / C)^B), x in pg/mL",
            "standards_pg_mL": [STANDARD_TOP_PG_ML / STANDARD_DILUTION ** i for i in range(N_STANDARDS)],
            "qc_levels_pg_mL": QC_LEVELS,
            "noise_model": noise,
            "layout": "cols 1-2 standards S1-S8 in duplicate; cols 3-12 duplicate pairs: "
                      "1 blank, 2 QC, 37 unknowns per plate",
        }, fh, indent=2)

    print(f"SIMULATED dataset written to {args.out}")
    print(f"  plates: {args.plates}, wells: {len(long_rows)}, samples+QC+blank: {len(truth_rows)}")
    print(f"  seed: {args.seed}, 4PL: {FOUR_PL}, well CV: {args.cv}")


if __name__ == "__main__":
    main()
